### ISSUE TITLE
Some thoughts about benchmark fairness/scores

### ISSUE THREAD

**Issue by phuslu** [madkins23/go-slog#4]
1. Currently I found that phuslu/log and phsym/zeroslog has no mutex to lock the writer. It is somehow reasonable because we suppose/except that the underlying writer will handle it. see [log.FileWriter](https://github.com/phuslu/log/blob/master/file.go#L46) and [lumberjack.Logger](https://github.com/natefinch/lumberjack/blob/v2.0/lumberjack.go#L112). But it seems that unfair for slog.JSONHandler and madkins23/flash because they hold mutex -- Although this does not have much impact on single-threaded throughtput testing.
2.  I notice that the `Disabled` benchmark result is unstable. It may be that the performance of each handler implementation is too close, so measurement result has jitter in every time.
3. I guess that the score of [samber/slog-logrus](https://pkg.go.dev/github.com/samber/slog-logrus) is too lower then its score will interfere with the scores of other handlers -- Might consider removing it?
4. In my experience, allocs is a bit import than nanos.  for example, a `200 ns/op + 0 allocs/op` call seems has a higher score than a `150 ns/op + 1 allocs/op` call by right.

**Comment by phuslu** [comment]
1. maybe phuslu/slog also needs introduce a `Extras` option to define this behavior and others(e.g. formats)
2. I have no good ideas about it
3. I raise this query because I found the handler score is too "crowded" in the top-right corner of graph. please ignore me if slog-logrus is still needed.
4. also "out of thin air", can be ignore too.

**Comment by phuslu** [comment]
And I found another handler authored by go team member https://github.com/seankhliao/svcrunner/blob/main/jsonlog/ , phuslu/slog and its implementation details are similar.

**Comment by madkins23** [comment]
> 3. I guess that the score of [samber/slog-logrus](https://pkg.go.dev/github.com/samber/slog-logrus) is too lower then its score will interfere with the scores of other handlers -- Might consider removing it?

I have pushed changes to the scoring page to provide drill-down views of the chart:

![image](https://github.com/madkins23/go-slog/assets/13398045/025c008a-6d6d-459a-86da-1e593917bc7d)

**Comment by madkins23** [comment]
In general this isn't so much as an "issue" as it is a "discussion". I noted one fix that I was already working on and I created a separate issue for the new slog handler. The rest of it should be noted in the `Discussions` area.
